<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="342-MCC02CNANNMD6M.local" failures="1" tests="2" name="Command line test" time="66.349" errors="0" timestamp="2023-03-12T11:45:00 IST">
  <testcase classname="complaintTest" name="validateUserCanSuccessfullyCreateAComplaint" time="51.495"/>
  <testcase classname="complaintTest" name="validateUserCanSuccessfullyLoginTotheSystem" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [4] but found [1]
at complaintTest.validateUserCanSuccessfullyLoginTotheSystem(complaintTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- validateUserCanSuccessfullyLoginTotheSystem -->
</testsuite> <!-- Command line test -->
